// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2509.Robot2016aMD;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLmotor;
    public static SpeedController driveTrainRmotor;
    public static Compressor pnuematicsCompressor1;
    public static DoubleSolenoid pnuematicsDblSol1;
    public static DoubleSolenoid pnuematicsDblSol2;
    public static DoubleSolenoid pnuematicsDblSol3;
    public static SpeedController elevatorSpeedController1;
    public static SpeedController elevatorSpeedController2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLmotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "Lmotor", (Talon) driveTrainLmotor);
        
        driveTrainRmotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "Rmotor", (Talon) driveTrainRmotor);
        
        pnuematicsCompressor1 = new Compressor(0);
        
        
        pnuematicsDblSol1 = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Pnuematics", "DblSol 1", pnuematicsDblSol1);
        
        pnuematicsDblSol2 = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Pnuematics", "DblSol 2", pnuematicsDblSol2);
        
        pnuematicsDblSol3 = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("Pnuematics", "DblSol 3", pnuematicsDblSol3);
        
        elevatorSpeedController1 = new Talon(2);
        LiveWindow.addActuator("Elevator", "Speed Controller 1", (Talon) elevatorSpeedController1);
        
        elevatorSpeedController2 = new Talon(3);
        LiveWindow.addActuator("Elevator", "Speed Controller 2", (Talon) elevatorSpeedController2);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
